# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleofferts', '0002_auto_20170404_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleofert',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'approved'), ('2', 'rejected')], default='0', max_length=1),
        ),
    ]
